# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'guifQNYRyH.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionOtomatik = QAction(MainWindow)
        self.actionOtomatik.setObjectName(u"actionOtomatik")
        self.actionManuel = QAction(MainWindow)
        self.actionManuel.setObjectName(u"actionManuel")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 791, 541))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.frame = QFrame(self.page)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(69, 49, 661, 441))
        self.frame.setStyleSheet(u"background-color: rgb(85, 0, 0);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.comboBox = QComboBox(self.frame)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(150, 110, 201, 31))
        self.comboBox.setStyleSheet(u"\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 0, 0);")
        self.sendBtn = QPushButton(self.frame)
        self.sendBtn.setObjectName(u"sendBtn")
        self.sendBtn.setGeometry(QRect(150, 270, 81, 41))
        font = QFont()
        font.setPointSize(12)
        self.sendBtn.setFont(font)
        self.sendBtn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.servoLabel = QLabel(self.frame)
        self.servoLabel.setObjectName(u"servoLabel")
        self.servoLabel.setGeometry(QRect(530, 120, 51, 31))
        font1 = QFont()
        font1.setPointSize(16)
        self.servoLabel.setFont(font1)
        self.servoLabel.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.servoLabel.setAlignment(Qt.AlignCenter)
        self.mesafeLabelOto2 = QLabel(self.frame)
        self.mesafeLabelOto2.setObjectName(u"mesafeLabelOto2")
        self.mesafeLabelOto2.setGeometry(QRect(530, 220, 51, 31))
        self.mesafeLabelOto2.setFont(font1)
        self.mesafeLabelOto2.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.mesafeLabelOto2.setAlignment(Qt.AlignCenter)
        self.mesafeLabelOto = QLabel(self.frame)
        self.mesafeLabelOto.setObjectName(u"mesafeLabelOto")
        self.mesafeLabelOto.setGeometry(QRect(530, 170, 51, 31))
        self.mesafeLabelOto.setFont(font1)
        self.mesafeLabelOto.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.mesafeLabelOto.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(430, 170, 101, 31))
        font2 = QFont()
        font2.setPointSize(14)
        self.label_5.setFont(font2)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(430, 220, 101, 31))
        self.label_7.setFont(font2)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(430, 120, 101, 31))
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.startBtnOto = QPushButton(self.frame)
        self.startBtnOto.setObjectName(u"startBtnOto")
        self.startBtnOto.setGeometry(QRect(440, 270, 81, 41))
        self.startBtnOto.setFont(font)
        self.startBtnOto.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.servo1 = QSlider(self.page_2)
        self.servo1.setObjectName(u"servo1")
        self.servo1.setGeometry(QRect(120, 350, 191, 31))
        self.servo1.setMinimum(1)
        self.servo1.setMaximum(180)
        self.servo1.setOrientation(Qt.Horizontal)
        self.servo2 = QSlider(self.page_2)
        self.servo2.setObjectName(u"servo2")
        self.servo2.setGeometry(QRect(450, 350, 191, 31))
        self.servo2.setMinimum(1)
        self.servo2.setMaximum(180)
        self.servo2.setOrientation(Qt.Horizontal)
        self.frame_2 = QFrame(self.page_2)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(60, 50, 681, 441))
        self.frame_2.setStyleSheet(u"background-color: rgb(85, 85, 0);")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(60, 250, 71, 31))
        self.label_9.setFont(font1)
        self.label_9.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(390, 250, 71, 31))
        self.label_10.setFont(font1)
        self.label_10.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 340, 91, 31))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(380, 340, 91, 31))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.mesafeLabel = QLabel(self.frame_2)
        self.mesafeLabel.setObjectName(u"mesafeLabel")
        self.mesafeLabel.setGeometry(QRect(390, 80, 71, 31))
        self.mesafeLabel.setFont(font1)
        self.mesafeLabel.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.mesafeLabel.setAlignment(Qt.AlignCenter)
        self.mesafeLabel2 = QLabel(self.frame_2)
        self.mesafeLabel2.setObjectName(u"mesafeLabel2")
        self.mesafeLabel2.setGeometry(QRect(390, 140, 71, 31))
        self.mesafeLabel2.setFont(font1)
        self.mesafeLabel2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.mesafeLabel2.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.frame_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(290, 80, 91, 31))
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.frame_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(290, 140, 91, 31))
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_17.setAlignment(Qt.AlignCenter)
        self.startBtnMan = QPushButton(self.frame_2)
        self.startBtnMan.setObjectName(u"startBtnMan")
        self.startBtnMan.setGeometry(QRect(100, 90, 61, 31))
        font3 = QFont()
        font3.setPointSize(10)
        self.startBtnMan.setFont(font3)
        self.startBtnMan.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.stopBtnMan = QPushButton(self.frame_2)
        self.stopBtnMan.setObjectName(u"stopBtnMan")
        self.stopBtnMan.setGeometry(QRect(100, 160, 61, 31))
        self.stopBtnMan.setFont(font3)
        self.stopBtnMan.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.stackedWidget.addWidget(self.page_2)
        self.frame_2.raise_()
        self.servo1.raise_()
        self.servo2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        font4 = QFont()
        font4.setPointSize(18)
        self.toolBar.setFont(font4)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.toolBar.addAction(self.actionOtomatik)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionManuel)

        self.retranslateUi(MainWindow)
        self.servo1.valueChanged.connect(self.label_9.setNum)
        self.servo2.valueChanged.connect(self.label_10.setNum)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOtomatik.setText(QCoreApplication.translate("MainWindow", u"Otomatik", None))
        self.actionManuel.setText(QCoreApplication.translate("MainWindow", u"Manuel", None))
        self.sendBtn.setText(QCoreApplication.translate("MainWindow", u"SEND", None))
        self.servoLabel.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.mesafeLabelOto2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.mesafeLabelOto.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"MESAFE 1:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"MESAFE 2:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"SERVO:", None))
        self.startBtnOto.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"SERVO 1", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"SERVO 2", None))
        self.mesafeLabel.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.mesafeLabel2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"MESAFE 1:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"MESAFE 2:", None))
        self.startBtnMan.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.stopBtnMan.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

